{{- $fullname := include "skythread-aadesh.fullname" . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}-deployment
  labels:
    app: {{ $fullname }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    version: "{{ $.Values.commitSha }}"
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ $fullname }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ $fullname }}
        release: {{ $.Release.Name }}
        version: {{ $.Values.commitSha }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: {{ $fullname }}
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ $fullname }}
        ports:
        - containerPort: {{ .Values.ports.containerPort }}
          protocol: TCP
          name: httpport
