# Default values for iot-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: skythread-demo
replicaCount: 1
commitSha: fa97fb26bd8cc28c8b4b3f1f8ee9426d5cc3a12d
gitCommitMessage: 'GitHub commit to merge'
gitDeployUser: "Anh Tran"

image:
  repository: skythreaddemobackend.azurecr.io/skythread-data-tokenization
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: merge.3756

ports:
  containerPort: 80

service:
  name: skythread-data-tokenization
  type: NodePort
  port: 80
  targetPort: 80

nameOverride: ""

fullnameOverride: "skythread-data-tokenization"

#livenessProbe:
#  path: /healthz
#  initialDelaySeconds: 5
#
#readinessProbe:
#  path: /healthz
#  initialDelaySeconds: 5

env:
  registrySecretName: skythreaddemobackend-acr
#  secretName: iam-user-management-secret-env
#  mountPath: /usr/src/app/.env

argocdHooks:
  - name: presync
    type: PreSync
    image: pstauffer/curl:latest
    command: ['/bin/sh']
    args:
      - '-c'
      - 'sh /tmp/send.sh'
    volumeMounts:
      - name: command-config
        mountPath: /tmp/send.sh
        subPath: send.sh
    volumes:
      - name: command-config
        configMap:
          name: argocd-hook
          defaultMode: 0755
  - name: postsync
    type: PostSync
    image: pstauffer/curl:latest
    command: ['/bin/sh']
    args:
      - '-c'
      - 'sh /tmp/send.sh'
    volumeMounts:
      - name: command-config
        mountPath: /tmp/send.sh
        subPath: send.sh
    volumes:
      - name: command-config
        configMap:
          name: argocd-hook
          defaultMode: 0755
