# Default values for iot-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: skythread-demo
replicaCount: 1
commitSha: 8d3f4de8eee1c4fe39c6fe9c035ad32b58883569
gitCommitMessage: 'Microsoft.VisualStudio.Services.TFS commit to Demo'
gitDeployUser: "Anh Tran"

image:
  repository: skythreaddemobackend.azurecr.io/skythread-hlf-middleware
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: Demo.3733

ports:
  containerPort: 80

service:
  name: skythread-hlf-middleware
  type: NodePort
  port: 7071
  targetPort: 7071

nameOverride: ""

fullnameOverride: "skythread-hlf-middleware"

#livenessProbe:
#  path: /healthz
#  initialDelaySeconds: 5
#
#readinessProbe:
#  path: /healthz
#  initialDelaySeconds: 5

env:
  registrySecretName: skythreaddemobackend-acr
#  secretName: iam-user-management-secret-env
#  mountPath: /usr/src/app/.env

argocdHooks:
  - name: presync
    type: PreSync
    image: pstauffer/curl:latest
    command: ['/bin/sh']
    args:
      - '-c'
      - 'sh /tmp/send.sh'
    volumeMounts:
      - name: command-config
        mountPath: /tmp/send.sh
        subPath: send.sh
    volumes:
      - name: command-config
        configMap:
          name: argocd-hook
          defaultMode: 0755
  - name: postsync
    type: PostSync
    image: pstauffer/curl:latest
    command: ['/bin/sh']
    args:
      - '-c'
      - 'sh /tmp/send.sh'
    volumeMounts:
      - name: command-config
        mountPath: /tmp/send.sh
        subPath: send.sh
    volumes:
      - name: command-config
        configMap:
          name: argocd-hook
          defaultMode: 0755
