# Default values for iot-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: skythread-demo
replicaCount: 1
commitSha: cade7a976b9f996b307e97f39672e3aa0216efbb
gitCommitMessage: 'Ninh Doan Thang (FHN.PMO) commit to azure-pipelines-demo-aks'
gitDeployUser: "Anh Tran"

image:
  repository: skythreaddemobackend.azurecr.io/authentication-svc
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: azure-pipelines-demo-aks.3670

ports:
  containerPort: 80

service:
  name: skythread-authentication-svc
  type: NodePort
  port: 80
  targetPort: 80

nameOverride: ""

fullnameOverride: "skythread-authentication-svc"

#livenessProbe:
#  path: /healthz
#  initialDelaySeconds: 5
#
#readinessProbe:
#  path: /healthz
#  initialDelaySeconds: 5

env:
  registrySecretName: skythreaddemobackend-acr
#  secretName: iam-user-management-secret-env
#  mountPath: /usr/src/app/.env

argocdHooks:
  - name: presync
    type: PreSync
    image: pstauffer/curl:latest
    command: ['/bin/sh']
    args:
      - '-c'
      - 'sh /tmp/send.sh'
    volumeMounts:
      - name: command-config
        mountPath: /tmp/send.sh
        subPath: send.sh
    volumes:
      - name: command-config
        configMap:
          name: argocd-hook
          defaultMode: 0755
  - name: postsync
    type: PostSync
    image: pstauffer/curl:latest
    command: ['/bin/sh']
    args:
      - '-c'
      - 'sh /tmp/send.sh'
    volumeMounts:
      - name: command-config
        mountPath: /tmp/send.sh
        subPath: send.sh
    volumes:
      - name: command-config
        configMap:
          name: argocd-hook
          defaultMode: 0755
